# uav1:
#   id: 1
#   x: -29.0
#   y: -24.0
#   z: 0.0
#   heading: -0.3

uav1:
  id: 1
  x: -14.0
  y: -30.0
  z: 0.0
  heading: -0.3

# uav2:
#   id: 2
#   x: 14.0
#   y: 7.5
#   z: 0.0
#   heading: 3.14

uav2:
  id: 2
  x: 0.0
  y: -40.0
  z: 0.0
  heading: 3.14

